### ISSUE TITLE
win10 怎么启动swoole

### ISSUE THREAD

**Issue by Felo-Z** [hhxsv5/docker#1]
容器运行正常，也运行正常，swoole无法启动

**Comment by hhxsv5** [comment]
参考[docker-compose](https://github.com/hhxsv5/docker)

**Comment by hhxsv5** [comment]
docker logs 看看具体错误。

**Comment by Felo-Z** [comment]
已经成功启动，
1、通过配置swoole的域名访问会直接下载index.php，nx错误，`directory index of "/docker/www/laravels/public/" is forbidden`；
2、通过未配置swoole的域名访问，一切正常；
两个nginx配置文件直接使用本项目中的配置文件，[laravel.conf](https://github.com/hhxsv5/docker/blob/master/nginx/conf.d/laravel.conf) 和 [laravels.conf](https://github.com/hhxsv5/docker/blob/master/nginx/conf.d/laravels.conf)，

**Comment by hhxsv5** [comment]
你指的”swoole的域名“是`laravels.com`？
“未配置swoole域名”是IP和端口访问？

**Comment by Felo-Z** [comment]
> 你指的”swoole的域名“是`laravels.com`？
> “未配置swoole域名”是IP和端口访问？
我表述有误，
1、通过swoole加速用的域名是laravles.com对应的配置文件是[laravels.conf](https://github.com/hhxsv5/docker/blob/master/nginx/conf.d/laravels.conf)，
2、未通过swoole加速用的是域名是laravel.com对应的配置文件是[laravel.conf](https://github.com/hhxsv5/docker/blob/master/nginx/conf.d/laravels.conf)

**Comment by hhxsv5** [comment]
检查public目录权限

**Comment by Felo-Z** [comment]
好了，
